### ISSUE TITLE
Tag releases - Package Control compatible

### ISSUE THREAD

**Issue by tboby** [Zednosius/StellarisSublime#2]
Could you possibly tag "Releases"? I think this is all that would be needed to make the repo Package Control compatible.

I've made another package that depends on a `stellaris.sublime-syntax` file, and I'd really like to be able to link to this package so that users can install it using Package Control.

Example from my package:
https://github.com/tboby/cwtools-sublime/releases

**Comment by Zednosius** [comment]
I went and added a release so hopefully, it should work now!
